[theme]
# Cor dos detalhes ativos, botões, sliders e links (--dourado)
primaryColor = "#704cf2"

# Cor de fundo principal (--fundo: cinza claro)
backgroundColor = "#F5F0FF"

# Cor dos painéis e caixas de texto lateral (--fundo-2: branco)
secondaryBackgroundColor = "#FFFFFF"

# Cor do texto principal (--texto: azul-petróleo)
textColor = "#5b0e93"

# Fonte padrão do sistema
font = "sans serif"